theme = "hugo-academic"
baseURL = "/"
languageCode = "en-us"
title = "kevin test"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""
copyright = "&copy; 2019 Kevin Xu ZHONG"




